### ISSUE TITLE
Mask reversing the numbers

### ISSUE THREAD

**Issue by jonathantsilva** [igorescobar/jQuery-Mask-Plugin#587] opened 2017-08-02 14:38 UTC
I created the following mask for the credit card number.
```javascript
$('.card-number').mask('0000 0000 0000 0000');
```
While typing the numbers (Chrome - Android), when it arrived in the mask the numbers were inverted because the cursor was 1 position behind.

Should be: 2345 6315
It was typed: 2345 3156

I fixed this by inserting `ctrl.setSelectionRange (200,200);` After line 64 on `mask.js`.
200 is an abitrary value that is much higher than the maximum of my input.

I found this solution here.
[https://css-tricks.com/snippets/jquery/move-cursor-to-end-of-textarea-or-input/](https://css-tricks.com/snippets/jquery/move-cursor-to-end-of-textarea-or-input/)

I hope this solution can help other users with the same problem.

```javascript
getCaret: function () {
    try {
        var sel,
            pos = 0,
            ctrl = el.get(0),
            dSel = document.selection,
            cSelStart = ctrl.selectionStart;
                    
       ctrl.setSelectionRange(200,200);
```

**Comment by rupeshdabbir** [comment] 2017-09-06 22:48
There's a problem with this approach. When you do a command+v it will automatically unselect everything (Since you are using selectionRange). The better way of handling this is here: https://github.com/igorescobar/jQuery-Mask-Plugin/pull/602

**Comment by igorescobar** [comment] 2017-09-28 09:15
The problem here is the same as related on the #602. Maybe you guys could join forces to get this sorted :-) 
As the problem is the same I will close this issue and then we can all discuss in only one of them, okay?

See you there.

**Closed by igorescobar** 2017-09-28 09:15 UTC
