### ISSUE TITLE
onKeyPress and onComplete events firing multiple times

### ISSUE THREAD

**Issue by ArthurPBressan** [igorescobar/jQuery-Mask-Plugin#353] opened 2015-10-17 15:54 UTC
I have the following snippet:

```javascript
$('#cep').mask('00000-000', {
    onKeyPress: function(cep) {
        console.log(cep);
    },
    onComplete: function(cep) {
        $('ul').append('<li>CEP digitado: '+ cep + '</li>');
    }
});
```
I expected that for each number typed in the CEP field, the CEP would be logged once and, when the input is complete, there would be only one new `li` item with the typed in CEP. However, as shown on the Chrome DevTools the CEP was logged twice on each new number and there would be two new `li`s appended to the `ul`.

I'm using jquery 2.1.4 and jquerymask 1.13.4

EDIT:  See jsfiddle at https://jsfiddle.net/d7p1vwjf/

**Comment by ArthurPBressan** [comment] 2015-10-17 16:00
Sometimes the onComplete fires multiple times as well.

**Comment by kevinchevallier** [comment] 2015-11-04 18:25
Just confirming that `onComplete` fires twice yes after entering the last value.
```
onComplete:function(){
    var v = $dateofbirth.val();
    console.log(v); 
```
Does display the value twice in the console on tying in the last number of a date of birth masked field.
And i've even seen the `onComplete` not firing at all.

**Comment by theo-bittencourt** [comment] 2015-11-05 17:04
One event is triggered when keydown and another when keyup.

**Comment by ArthurPBressan** [comment] 2015-11-10 00:21
@kevinchevallier 

I'm pretty sure I'm not calling mask twice, as that example was enough to show the problem, but yeah, it doesn't cost anything to check yet again. :)

I think a fiddle will work best, but I'm kinda busy to do that right now.

**Comment by ArthurPBressan** [comment] 2015-11-15 17:13
I prepared a fiddle using the above snippet: 
https://jsfiddle.net/d7p1vwjf/

It shows that you don't need to call `.mask()` twice for the problem to show.

**Comment by igorescobar** [comment] 2015-12-04 18:15
It's called twice because there is two events being triggered the `input` and the `keyup`. Needs to be fixed... I'm going to figure it out.

**Comment by ArthurPBressan** [comment] 2015-12-04 18:26
Thank you!

**Comment by dtelaroli** [comment] 2015-12-23 12:44
I don't know if it's related, but when I use the São Paulo Mask Behavior example I get a infinite loop in console.

**Comment by igorescobar** [comment] 2016-03-06 21:44
Fixed on coming up new version.

**Closed by igorescobar** 2016-03-06 21:44 UTC
Labels: bug

**Comment by Rhend** [comment] 2016-06-27 12:23
On version 1.14.0 the problem is still here. To be more accurate, in the fiddle, if i type 00000-000 everything is fine. But if i continue to type 000000000 after that, the mask lock the typing but the Event OnComplete load every type in memory and execute for each 0 we type the code in OnComplete.

Maybe it's not a real bug but if we execute some data mining on the OnComplete event, it's not fiable at all
