### ISSUE TITLE
Samsung A7 still with cursor movement bug

### ISSUE THREAD

**Issue by pixem** [igorescobar/jQuery-Mask-Plugin#529] opened 2017-03-20 19:28 UTC
The bug with the cursor positioning still continues. One of our clients still reports a jump when typing CEP (zipcode) in your demo website (https://igorescobar.github.io/jQuery-Mask-Plugin/). I read all the comments on #464. Instead of 12345-678, becomes 12345-786. The mobile field is ok. Here's the mobile info: 
- keyboard: Samsung (QUERTY-PortBR)
- browser: Chrome 56.0.2924.87
- mobile model: Samsung A7 2016
- mobile version: SM-A710M
- Android: 5.1.1.

![afe2d1795d643cd7437e2f8965a5bbc6d37fe91b28cc1246ec pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/26554058/24117750/27e19de2-0d8a-11e7-8884-8ce0634685a1.jpg)

**Comment by jeanjap** [comment] 2017-03-21 16:50
A similar problem happens in Chrome Desktop. Version 56.0.2924.87 (64-bit).
In the "Telephone with Code Area" field, if the user types the area code, then leaves the field and returns. When typing again, the cursor position is incorrect.

To reproduce the error:

Enter 2 numbers. Ex: (41
Get out of the field.
Return to the field using SHIFT + TAB.
Please enter a number. The result will be: (14

What it seems is that the error only occurs when the value in the field is selected.

**Comment by jeanjap** [comment] 2017-03-21 17:15
Possible Solution:

https://jsfiddle.net/jeanjap/fms4cmqh/7/

**Comment by katugtug** [comment] 2017-03-21 18:19
@jeanjap Because shift-tab selects all, that's what causes it. That's the same as this open issue:  https://github.com/igorescobar/jQuery-Mask-Plugin/issues/509

**Comment by igorescobar** [comment] 2017-05-30 21:14
I believe this is fixed now. Thanks!

**Closed by igorescobar** 2017-05-30 21:14 UTC

**Comment by jeanjap** [comment] 2017-05-31 12:02
Tanks! Working for me!
https://jsfiddle.net/jeanjap/fms4cmqh/7/
