### ISSUE TITLE
unmask() does not remove the "maxlength" attribute

### ISSUE THREAD

**Issue by kefir500** [igorescobar/jQuery-Mask-Plugin#507] opened 2017-01-18 09:43 UTC
Version [**1.14.2**](https://github.com/igorescobar/jQuery-Mask-Plugin/releases/tag/v1.14.2) adds the next feature:
> apply auto maxlength in case the mask doesn't have recursive pattern

However, the `unmask()` function **does not** remove the `maxlength` attribute added by this behavior, and the unmasked input length is still limited by the previously set mask pattern.

Example: [https://jsfiddle.net/t2cakzgb/3](https://jsfiddle.net/t2cakzgb/3)

The affected versions are **1.14.2** to the current (**1.14.8**).  
The temporary solution is to manually call the `removeAttr('maxlength')`.

**Comment by nunesbeto** [comment] 2017-01-18 12:40
+1

**Comment by chirogamer** [comment] 2017-01-31 01:55
what is this

**Comment by pedrofurtado** [comment] 2017-04-27 17:34
@igorescobar Any news about this issue?

Because I am having the same issue. Here is my example in JSFiddle: https://jsfiddle.net/13cqy6jy/2/

Even calling *unmask()* function, the attribute "maxlength" is not removed from input tag.

Is it possible to make something like this in source code of library?

```javascript
$.fn.unmask = function() {
        clearInterval($.maskWatchers[this.selector]);
        delete $.maskWatchers[this.selector];
        return this.each(function() {
            var dataMask = $(this).data('mask');
            if (dataMask) {
                dataMask.remove().removeData('mask');
            }

            $(this).removeAttr('maxlength'); // <- Hereis the new code!
        });
    };
```

**Comment by igorescobar** [comment] 2017-06-05 12:31
I will fix it asap, no problem.

**Comment by andraeinstein** [comment] 2017-09-08 09:44
is this already fixed? 
Any news 'bout this issue?

**Comment by natezander** [comment] 2017-11-01 19:20
I still see this bug in version 1.14.12

**Comment by nusendra** [comment] 2017-11-02 03:31
is this bug still exists?

**Comment by dougjohnston** [comment] 2017-12-19 17:04
Still seeing this bug in 1.14.13.

**Comment by nusendra** [comment] 2017-12-20 00:09
Now i'm playing with vue, i dont use this anymore

**Comment by pedrofurtado** [comment] 2017-12-20 14:44
@igorescobar Any news about this issue?

**Comment by vonsky104** [comment] 2018-02-28 13:04
Guys, what @pedrofurtado said is working, just find fn.unmask function in jquery.mask.js and paste 
`$(this).removeAttr('maxlength');` just after
`  if (dataMask) {
                dataMask.remove().removeData('mask');
            }`
Thanks for that I can now mask, then unmask and mask again (I had a select with different Phone numbers from different countries and input masks needed to be different).

**Comment by pedrofurtado** [comment] 2018-02-28 22:54
@igorescobar Any news about this issue?

**Comment by marcioJesus** [comment] 2018-03-01 14:55
Any news?

**Comment by pedrofurtado** [comment] 2018-03-16 17:19
Bug fixed in version "v1.14.14".

**Comment by igorescobar** [comment] 2018-03-16 17:20
Enjoy ;)

**Closed** 2018-03-16 17:20 UTC
Labels: bug

**Comment by DylanDelobel** [comment] 2019-02-22 14:33
Bug still exists in version `v1.14.15` and `v1.14.14`

To reproduce take the first jsfiddle and change the library version
